import { Location } from "../schemas/location.schema";
import { Victim } from "../schemas/victim.schema";

export const locations: (Omit<
  Location,
  "id" | "createdAt" | "updatedAt" | "labelId"
> & {
  victims: Omit<Victim, "id" | "createdAt" | "updatedAt" | "locationId">[];
})[] = [
  {
    summary: "Có 1 người bị tai nạn giao thông, cần xe cứu thương.",
    note: "Nạn nhân mất máu nhiều, ý thức lơ mơ. Khu vực xung quanh ngập nước, phương tiện tiếp cận khó khăn.",
    lat: 10.748995876816066,
    lng: 106.7183670037111,
    address: "Đường D2, Tân Thuận Tây, Quận 7, Hồ Chí Minh, Vietnam",
    emergencyLevel: "critical",
    tags: [
      "Cần cứu hộ giao thông",
      "Cần xe cứu thương",
      "Ngập nước",
      "Ý thức nạn nhân giảm",
      "Kẹt xe",
    ],
    victims: [
      {
        fullname: "Nguyễn Văn A",
        phone: "0901234567",
        phone2: "0912345678",
        email: "nguyenvana@gmail.com",
        age: 20,
        gender: "male",
        note: "",
        facebookURL: null,
        conversations: [],
        addressText: "",
      },
    ],
  },
  {
    summary: "Gia đình 3 người bị mắc kẹt trong ngôi nhà ngập nước do bão lũ.",
    note: "Nước ngập tận tầng 1, cần lực lượng cứu hộ hỗ trợ di tản khẩn cấp. Có trẻ nhỏ và người lớn tuổi.",
    lat: 10.758995,
    lng: 106.666667,
    address: "15 Nguyễn Thị Thập, P. Bình Thuận, Quận 7, Hồ Chí Minh",
    emergencyLevel: "high",
    tags: ["Cần di tản", "Gia đình mắc kẹt", "Ngập sâu", "Có trẻ em", "Bão lũ"],
    victims: [
      {
        fullname: "Trần Minh Quân",
        phone: "0912223334",
        phone2: null,
        email: "tranminhquan1980@gmail.com",
        age: 43,
        gender: "male",
        note: "Bị bệnh tiểu đường, khó di chuyển nhanh.",
        facebookURL: null,
        conversations: [],
        addressText: "Tầng 2, 15 Nguyễn Thị Thập",
      },
      {
        fullname: "Nguyễn Thị Hồng",
        phone: "0934555666",
        phone2: null,
        email: "hongnguyen2000@gmail.com",
        age: 40,
        gender: "female",
        note: "Lo lắng cho con nhỏ, không biết bơi.",
        facebookURL: null,
        conversations: [],
        addressText: "Cùng địa chỉ, phòng khác",
      },
      {
        fullname: "Trần Minh Khoa",
        phone: null,
        phone2: null,
        email: null,
        age: 8,
        gender: "male",
        note: "Bị ốm, có dấu hiệu sốt cao.",
        facebookURL: null,
        conversations: [],
        addressText: "Tầng 2, cùng gia đình",
      },
    ],
  },
  {
    summary:
      "Người già bị mắc kẹt trên sân thượng nhà 4 tầng do nước lũ dâng cao.",
    note: "Không đủ nước sạch, sức khỏe yếu. Không tự xuống đất an toàn được.",
    lat: 10.780012,
    lng: 106.700148,
    address: "95 Trần Não, P. Bình An, TP Thủ Đức, TP Hồ Chí Minh",
    emergencyLevel: "critical",
    tags: [
      "Cần cứu hộ/di tản",
      "Người già",
      "Thiếu nước sạch",
      "Ngập lụt nặng",
    ],
    victims: [
      {
        fullname: "Lê Văn Hòa",
        phone: "0988124829",
        phone2: null,
        email: "hoale@gmail.com",
        age: 72,
        gender: "male",
        note: "Bị huyết áp cao, khó thở khi trời nóng.",
        facebookURL: null,
        conversations: [],
        addressText: "Sân thượng, nhà số 95 Trần Não",
      },
    ],
  },
  {
    summary:
      "2 công nhân bị mắc kẹt tại công trình xây dựng do nước lên nhanh sau mưa lớn.",
    note: "Cả hai đều mất liên lạc điện thoại, chỉ còn sóng yếu. Kêu cứu từ tối qua.",
    lat: 10.805321,
    lng: 106.716503,
    address: "Ngã tư Nguyễn Oanh - Quang Trung, Gò Vấp, Hồ Chí Minh",
    emergencyLevel: "high",
    tags: [
      "Cần cứu hộ",
      "Công nhân mắc kẹt",
      "Nước lũ dâng nhanh",
      "Thiếu thực phẩm",
    ],
    victims: [
      {
        fullname: "Phạm Quốc Đạt",
        phone: "0968234923",
        phone2: null,
        email: null,
        age: 31,
        gender: "male",
        note: "Bị thương nhẹ ở chân, không thể lội nước ra ngoài.",
        facebookURL: null,
        conversations: [],
        addressText: "Trên tầng 2 công trình",
      },
      {
        fullname: "Trương Minh Hạnh",
        phone: "0972455667",
        phone2: null,
        email: null,
        age: 28,
        gender: "female",
        note: "Rất sợ nước, tâm lý hoảng loạn.",
        facebookURL: null,
        conversations: [],
        addressText: "Cùng vị trí với Quốc Đạt",
      },
    ],
  },
  {
    summary:
      "Nhóm 5 hộ dân bị cô lập do sạt lở đất chặn đường duy nhất ra ngoài.",
    note: "Khu vực vùng núi, đường bị sạt lở hoàn toàn. Cần trực thăng hoặc đội cứu hộ đường rừng. Lương thực còn đủ khoảng 2 ngày.",
    lat: 10.832145,
    lng: 106.623789,
    address: "Ấp 3, Xã Xuân Thới Thượng, Hóc Môn, TP.HCM",
    emergencyLevel: "high",
    tags: [
      "Sạt lở đất",
      "Cô lập",
      "Cần tiếp tế lương thực",
      "Đường bị chặn",
    ],
    victims: [
      {
        fullname: "Huỳnh Văn Tám",
        phone: "0911234567",
        phone2: null,
        email: null,
        age: 55,
        gender: "male",
        note: "Trưởng ấp, đại diện liên lạc cho 5 hộ gia đình.",
        facebookURL: null,
        conversations: [],
        addressText: "Ấp 3, gần chân đồi",
      },
      {
        fullname: "Nguyễn Thị Tuyết",
        phone: "0933456789",
        phone2: null,
        email: null,
        age: 67,
        gender: "female",
        note: "Bị viêm phổi mãn tính, cần thuốc gấp.",
        facebookURL: null,
        conversations: [],
        addressText: "Nhà cạnh nhà ông Tám",
      },
    ],
  },
  {
    summary: "Cháy lớn tại khu trọ công nhân, 4 người mắc kẹt bên trong.",
    note: "Đám cháy bùng phát lúc 2h sáng, lối thoát hiểm bị chặn. Đã gọi PCCC nhưng xe chưa tới do ngập nước.",
    lat: 10.823456,
    lng: 106.678901,
    address: "Hẻm 47 Phan Huy Ích, P.14, Q.Gò Vấp, TP.HCM",
    emergencyLevel: "critical",
    tags: ["Cháy", "Mắc kẹt", "Khu trọ", "Cần PCCC", "Lối thoát bị chặn"],
    victims: [
      {
        fullname: "Đặng Văn Phúc",
        phone: "0965432109",
        phone2: null,
        email: "dangvanphuc@gmail.com",
        age: 26,
        gender: "male",
        note: "Bị bỏng nhẹ tay phải, vẫn còn tỉnh táo.",
        facebookURL: "https://facebook.com/dangvanphuc",
        conversations: [],
        addressText: "Phòng 3, tầng 2 khu trọ",
      },
      {
        fullname: "Lê Thị Mai",
        phone: "0978123456",
        phone2: null,
        email: null,
        age: 24,
        gender: "female",
        note: "Hít phải nhiều khói, khó thở.",
        facebookURL: null,
        conversations: [],
        addressText: "Phòng 4, tầng 2 khu trọ",
      },
      {
        fullname: "Trần Quốc Huy",
        phone: null,
        phone2: null,
        email: null,
        age: 30,
        gender: "male",
        note: "Bất tỉnh, cần sơ cứu ngay.",
        facebookURL: null,
        conversations: [],
        addressText: "Phòng 5, tầng 3 khu trọ",
      },
      {
        fullname: "Phan Thị Ngọc",
        phone: "0899876543",
        phone2: null,
        email: null,
        age: 22,
        gender: "female",
        note: "Đang mang thai tháng thứ 7.",
        facebookURL: null,
        conversations: [],
        addressText: "Phòng 6, tầng 3 khu trọ",
      },
    ],
  },
  {
    summary:
      "Xe buýt bị ngập nước chết máy giữa đường, 20 hành khách cần di tản.",
    note: "Nước ngập quá nửa bánh xe, hành khách hoảng loạn. Có người lớn tuổi và trẻ em trên xe.",
    lat: 10.771234,
    lng: 106.691234,
    address: "Đường Nguyễn Hữu Cảnh, P.22, Q.Bình Thạnh, TP.HCM",
    emergencyLevel: "high",
    tags: [
      "Xe buýt ngập nước",
      "Di tản hành khách",
      "Đường ngập",
      "Có người già",
      "Có trẻ em",
    ],
    victims: [
      {
        fullname: "Tài xế Nguyễn Hùng",
        phone: "0945678901",
        phone2: null,
        email: null,
        age: 48,
        gender: "male",
        note: "Tài xế xe buýt, đang cố giữ bình tĩnh cho hành khách.",
        facebookURL: null,
        conversations: [],
        addressText: "Trên xe buýt tuyến 53",
      },
      {
        fullname: "Bà Trần Thị Phượng",
        phone: "0913567890",
        phone2: null,
        email: null,
        age: 75,
        gender: "female",
        note: "Bị tăng huyết áp, chóng mặt.",
        facebookURL: null,
        conversations: [],
        addressText: "Hành khách trên xe",
      },
    ],
  },
  {
    summary:
      "Sập mái nhà xưởng do gió giật mạnh, 2 người bị đè dưới đống đổ nát.",
    note: "Kết cấu tôn và sắt đổ sập, cần máy cắt và đội cứu hộ chuyên nghiệp. Tiếng kêu cứu yếu dần.",
    lat: 10.854321,
    lng: 106.645678,
    address: "KCN Vĩnh Lộc, Bình Chánh, TP.HCM",
    emergencyLevel: "critical",
    tags: [
      "Sập nhà xưởng",
      "Bị đè",
      "Cần máy cắt",
      "Gió giật",
      "Cần cứu hộ khẩn",
    ],
    victims: [
      {
        fullname: "Hoàng Minh Tú",
        phone: "0922345678",
        phone2: "0987234567",
        email: "hoangminhtu@gmail.com",
        age: 35,
        gender: "male",
        note: "Bị kẹt chân dưới dầm sắt, vẫn còn tỉnh, đau nhiều.",
        facebookURL: null,
        conversations: [],
        addressText: "Khu vực xưởng B2",
      },
      {
        fullname: "Võ Thị Thanh",
        phone: null,
        phone2: null,
        email: null,
        age: 29,
        gender: "female",
        note: "Không nghe thấy phản hồi từ 30 phút trước.",
        facebookURL: null,
        conversations: [],
        addressText: "Gần khu vực xưởng B2",
      },
    ],
  },
  {
    summary: "Trẻ em bị lạc mẹ trong khu sơ tán tập trung.",
    note: "Bé gái khoảng 5 tuổi, khóc nhiều, không nhớ số điện thoại mẹ. Được người dân đưa tới điểm sơ tán.",
    lat: 10.762345,
    lng: 106.654321,
    address: "Trường TH Lê Quý Đôn, P. Tân Kiểng, Q.7, TP.HCM",
    emergencyLevel: "medium",
    tags: ["Trẻ lạc", "Cần tìm gia đình", "Điểm sơ tán"],
    victims: [
      {
        fullname: "Bé Ngọc (chưa rõ họ)",
        phone: null,
        phone2: null,
        email: null,
        age: 5,
        gender: "female",
        note: "Mặc áo hồng, quần jean. Nói mẹ tên Hoa, ở gần chợ.",
        facebookURL: null,
        conversations: [],
        addressText: "Điểm sơ tán trường TH Lê Quý Đôn",
      },
    ],
  },
  {
    summary:
      "Nhà dân bị ngập sâu 1.5m, gia đình 4 người leo lên gác lửng chờ cứu hộ.",
    note: "Khu vực trũng, nước vẫn đang lên. Đồ đạc, thức ăn đều bị ngập. Cần xuồng cứu hộ.",
    lat: 10.737890,
    lng: 106.735678,
    address: "Hẻm 302 Lê Văn Lương, Nhà Bè, TP.HCM",
    emergencyLevel: "high",
    tags: ["Ngập sâu", "Gia đình mắc kẹt", "Cần xuồng", "Thiếu thực phẩm"],
    victims: [
      {
        fullname: "Đỗ Quang Vinh",
        phone: "0916789012",
        phone2: null,
        email: "doquangvinh85@gmail.com",
        age: 40,
        gender: "male",
        note: "Đang bảo vệ gia đình trên gác lửng.",
        facebookURL: null,
        conversations: [],
        addressText: "Gác lửng, hẻm 302 Lê Văn Lương",
      },
      {
        fullname: "Đỗ Thị Hằng",
        phone: "0987654123",
        phone2: null,
        email: null,
        age: 38,
        gender: "female",
        note: "Lo lắng cho hai con nhỏ.",
        facebookURL: null,
        conversations: [],
        addressText: "Cùng gia đình",
      },
      {
        fullname: "Đỗ Minh Anh",
        phone: null,
        phone2: null,
        email: null,
        age: 10,
        gender: "female",
        note: "Bị cảm lạnh, sốt nhẹ.",
        facebookURL: null,
        conversations: [],
        addressText: "Cùng gia đình",
      },
      {
        fullname: "Đỗ Gia Bảo",
        phone: null,
        phone2: null,
        email: null,
        age: 6,
        gender: "male",
        note: "Sợ nước, khóc liên tục.",
        facebookURL: null,
        conversations: [],
        addressText: "Cùng gia đình",
      },
    ],
  },
  {
    summary:
      "Cụ bà sống một mình bị mắc kẹt do cây đổ chắn cửa nhà sau bão.",
    note: "Cây cổ thụ đổ chắn toàn bộ lối ra vào. Bà cần thuốc huyết áp hàng ngày và đã hết thuốc.",
    lat: 10.795432,
    lng: 106.652345,
    address: "198/5 Lạc Long Quân, P.3, Q.11, TP.HCM",
    emergencyLevel: "medium",
    tags: [
      "Cây đổ",
      "Người già sống một mình",
      "Cần thuốc",
      "Lối ra bị chặn",
    ],
    victims: [
      {
        fullname: "Nguyễn Thị Bích",
        phone: "0908765432",
        phone2: null,
        email: null,
        age: 82,
        gender: "female",
        note: "Bị tiểu đường và huyết áp cao, hết thuốc từ hôm qua.",
        facebookURL: null,
        conversations: [],
        addressText: "Nhà 198/5 Lạc Long Quân",
      },
    ],
  },
  {
    summary:
      "Nhóm sinh viên tình nguyện bị lật thuyền khi đi cứu trợ, 3 người mất tích.",
    note: "Thuyền bị lật do dòng nước chảy xiết. 2 người đã bơi vào bờ an toàn, 3 người còn lại chưa tìm thấy.",
    lat: 10.812345,
    lng: 106.758901,
    address: "Sông Sài Gòn, đoạn gần cầu Bình Lợi, Bình Thạnh, TP.HCM",
    emergencyLevel: "critical",
    tags: [
      "Lật thuyền",
      "Mất tích",
      "Nước chảy xiết",
      "Cần đội lặn",
      "Sinh viên tình nguyện",
    ],
    victims: [
      {
        fullname: "Lâm Hoàng Phúc",
        phone: "0941234567",
        phone2: null,
        email: "lamhoangphuc@gmail.com",
        age: 21,
        gender: "male",
        note: "Mất tích, biết bơi nhưng nước chảy rất mạnh.",
        facebookURL: "https://facebook.com/lamhoangphuc",
        conversations: [],
        addressText: "Khu vực gần cầu Bình Lợi",
      },
      {
        fullname: "Trịnh Ngọc Diễm",
        phone: "0923456789",
        phone2: null,
        email: "trinhngocdiem@gmail.com",
        age: 20,
        gender: "female",
        note: "Mất tích, không biết bơi.",
        facebookURL: null,
        conversations: [],
        addressText: "Khu vực gần cầu Bình Lợi",
      },
      {
        fullname: "Cao Thanh Tùng",
        phone: "0967890123",
        phone2: null,
        email: null,
        age: 22,
        gender: "male",
        note: "Mất tích, mặc áo phao nhưng dòng nước quá mạnh.",
        facebookURL: null,
        conversations: [],
        addressText: "Khu vực gần cầu Bình Lợi",
      },
    ],
  },
  {
    summary:
      "Điện bị chập gây giật, 1 người bất tỉnh tại khu vực ngập nước.",
    note: "Dây điện rơi xuống vùng ngập, nguy hiểm cao cho khu vực xung quanh. Cần cắt điện khẩn cấp trước khi cứu hộ.",
    lat: 10.745678,
    lng: 106.709876,
    address: "Đường Huỳnh Tấn Phát, P. Tân Thuận Đông, Q.7, TP.HCM",
    emergencyLevel: "critical",
    tags: [
      "Điện giật",
      "Ngập nước",
      "Nguy hiểm cao",
      "Cần cắt điện",
      "Bất tỉnh",
    ],
    victims: [
      {
        fullname: "Bùi Thanh Phong",
        phone: "0956789012",
        phone2: null,
        email: null,
        age: 45,
        gender: "male",
        note: "Bất tỉnh sau khi bị điện giật, nằm trên nền nước ngập. KHÔNG tiếp cận khi chưa cắt điện.",
        facebookURL: null,
        conversations: [],
        addressText: "Trước nhà 112 Huỳnh Tấn Phát",
      },
    ],
  },
];
