import { Rescuer } from "../schemas/rescuer.schema";

export const rescuers: Omit<Rescuer, "id" | "createdAt" | "updatedAt">[] = [
  {
    fullName: "Nguyễn Văn An",
    phone: "0901234567",
    email: "nguyenvanan@gmail.com",
    secondaryPhone: "0912345678",
    address: "123 Lý Thường Kiệt, P.7, Q.10, TP.HCM",
    role: "medic",
    status: "available",
    experienceLevel: "senior",
    certifications: ["Bằng sơ cứu", "Bằng y tế dự phòng"],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Kinh nghiệm tham gia cứu trợ miền Trung 2020",
  },
  {
    fullName: "Trần Thị Bảo",
    phone: "0909123456",
    email: "tranthibao@gmail.com",
    secondaryPhone: null,
    address: "45 Nguyễn Huệ, Q.1, TP.HCM",
    role: "coordinator",
    status: "on_mission",
    experienceLevel: "lead",
    certifications: ["Chứng nhận quản lý cứu nạn"],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Tốt nghiệp đại học ngành quản trị khẩn cấp",
  },
  {
    fullName: "Lê Hữu Toàn",
    phone: "0988456231",
    email: "lehuutoan@gmail.com",
    secondaryPhone: "0988234567",
    address: "21 Lê Lợi, Q.Hải Châu, Đà Nẵng",
    role: "mountain_rescue",
    status: "off_duty",
    experienceLevel: "intermediate",
    certifications: ["HL cứu hộ núi"],
    region: "Đà Nẵng",
    avatarUrl: null,
    note: "Có thể tham gia các nhiệm vụ leo núi",
  },
  {
    fullName: "Phạm Minh Khoa",
    phone: "0937654321",
    email: "phamminhkhoa@gmail.com",
    secondaryPhone: null,
    address: "102 Phan Đình Phùng, Q.Phú Nhuận, TP.HCM",
    role: "firefighter",
    status: "injured",
    experienceLevel: "senior",
    certifications: ["Bằng PCCC"],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Đang nghỉ dưỡng thương, sẽ quay lại sớm",
  },
  {
    fullName: "Đinh Thị Quỳnh",
    phone: "0888765432",
    email: "dinhthiquynh@gmail.com",
    secondaryPhone: "0822123456",
    address: "75 Quang Trung, P.10, Q.Gò Vấp, TP.HCM",
    role: "medic",
    status: "available",
    experienceLevel: "junior",
    certifications: ["Chứng nhận y tế cơ bản"],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Sinh viên năm cuối ngành y",
  },
  {
    fullName: "Võ Thanh Sơn",
    phone: "0977123444",
    email: "vothanhson@gmail.com",
    secondaryPhone: null,
    address: "56 Trần Phú, Q.Nha Trang, Khánh Hòa",
    role: "diver",
    status: "available",
    experienceLevel: "intermediate",
    certifications: ["Bằng lặn cấp quốc gia"],
    region: "Khánh Hòa",
    avatarUrl: null,
    note: "Kinh nghiệm cứu hộ biển",
  },
  {
    fullName: "Bùi Thị Lan",
    phone: "0912988776",
    email: "buithilan@gmail.com",
    secondaryPhone: null,
    address: "88 Bạch Mai, Q.Hai Bà Trưng, Hà Nội",
    role: "logistics",
    status: "on_mission",
    experienceLevel: "senior",
    certifications: ["Chứng nhận logistics cứu trợ"],
    region: "Hà Nội",
    avatarUrl: null,
    note: "Phụ trách hậu cần nhiều chiến dịch lớn",
  },
  {
    fullName: "Ngô Văn Kiên",
    phone: "0905778112",
    email: "ngovankien@gmail.com",
    secondaryPhone: "0987444555",
    address: "14 Phạm Văn Đồng, P.Bình Thọ, Thủ Đức, TP.HCM",
    role: "firefighter",
    status: "available",
    experienceLevel: "junior",
    certifications: ["Chứng nhận huấn luyện PCCC"],
    region: "TP.HCM",
    avatarUrl: null,
    note: "Nhiệt huyết, sức khỏe tốt",
  },
  {
    fullName: "Lý Mỹ Hạnh",
    phone: "0934112233",
    email: "lymyhanh@gmail.com",
    secondaryPhone: null,
    address: "67 Hoàng Hoa Thám, Q.Ba Đình, Hà Nội",
    role: "coordinator",
    status: "off_duty",
    experienceLevel: "lead",
    certifications: ["Bằng điều phối cấp cao"],
    region: "Hà Nội",
    avatarUrl: null,
    note: "Từng là trưởng nhóm cứu hộ miền bắc",
  },
  {
    fullName: "Phạm Duy Tùng",
    phone: "0899122001",
    email: "phamduytung@gmail.com",
    secondaryPhone: null,
    address: "12 Điện Biên Phủ, Q.Bình Thạnh, TP.HCM",
    role: "mountain_rescue",
    status: "on_mission",
    experienceLevel: "senior",
    certifications: ["HL cứu hộ chuyên nghiệp", "Chứng nhận rừng núi nâng cao"],
    region: "TP.HCM",
    avatarUrl: null,
    note: "Tham gia huấn luyện cứu hộ quốc tế",
  },
  {
    fullName: "Hoàng Thị Yến",
    phone: "0918345612",
    email: "hoangthiyen@gmail.com",
    secondaryPhone: null,
    address: "30 Hùng Vương, Q.5, TP.HCM",
    role: "medic",
    status: "available",
    experienceLevel: "senior",
    certifications: ["Bằng bác sĩ đa khoa", "Chứng nhận cấp cứu ngoại viện"],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Bác sĩ bệnh viện Chợ Rẫy, tình nguyện cứu hộ",
  },
  {
    fullName: "Trương Văn Lộc",
    phone: "0976543210",
    email: "truongvanloc@gmail.com",
    secondaryPhone: "0911234567",
    address: "8 Nguyễn Văn Linh, Q.Thanh Khê, Đà Nẵng",
    role: "diver",
    status: "on_mission",
    experienceLevel: "senior",
    certifications: [
      "Bằng lặn PADI Advanced",
      "Chứng nhận cứu hộ dưới nước quốc tế",
    ],
    region: "Đà Nẵng",
    avatarUrl: null,
    note: "15 năm kinh nghiệm lặn, chuyên gia tìm kiếm dưới nước",
  },
  {
    fullName: "Phan Nhật Minh",
    phone: "0863456789",
    email: "phannhatminh@gmail.com",
    secondaryPhone: null,
    address: "22A Hai Bà Trưng, Q.Ninh Kiều, Cần Thơ",
    role: "logistics",
    status: "available",
    experienceLevel: "intermediate",
    certifications: ["Chứng nhận quản lý kho cứu trợ"],
    region: "Cần Thơ",
    avatarUrl: null,
    note: "Phụ trách phân phối hàng cứu trợ khu vực ĐBSCL",
  },
  {
    fullName: "Vũ Đức Anh",
    phone: "0847654321",
    email: "vuducanh@gmail.com",
    secondaryPhone: "0912876543",
    address: "156 Lê Duẩn, Q.Hải Châu, Đà Nẵng",
    role: "firefighter",
    status: "available",
    experienceLevel: "senior",
    certifications: ["Bằng PCCC chuyên nghiệp", "Chứng nhận cứu nạn hóa chất"],
    region: "Đà Nẵng",
    avatarUrl: null,
    note: "Đội trưởng PCCC quận Hải Châu, 12 năm kinh nghiệm",
  },
  {
    fullName: "Nguyễn Thanh Tâm",
    phone: "0935678901",
    email: "nguyenthanhtam@gmail.com",
    secondaryPhone: null,
    address: "77 Võ Thị Sáu, Q.3, TP.HCM",
    role: "coordinator",
    status: "available",
    experienceLevel: "senior",
    certifications: [
      "Chứng nhận điều phối thiên tai",
      "Bằng quản trị khẩn cấp nâng cao",
    ],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Từng điều phối cứu trợ bão Yagi 2024",
  },
  {
    fullName: "Lê Minh Đức",
    phone: "0856789012",
    email: "leminhduc@gmail.com",
    secondaryPhone: null,
    address: "45 Trần Cao Vân, Q.Phú Nhuận, TP.HCM",
    role: "mountain_rescue",
    status: "off_duty",
    experienceLevel: "intermediate",
    certifications: ["HL cứu hộ núi rừng", "Chứng nhận sinh tồn hoang dã"],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Hướng dẫn viên leo núi, thường xuyên tham gia tìm kiếm cứu nạn",
  },
  {
    fullName: "Đoàn Thị Ngọc Ánh",
    phone: "0878901234",
    email: "doanthingocanh@gmail.com",
    secondaryPhone: "0901567890",
    address: "10 Ngô Quyền, Q.Sơn Trà, Đà Nẵng",
    role: "medic",
    status: "on_mission",
    experienceLevel: "intermediate",
    certifications: ["Bằng điều dưỡng", "Chứng nhận sơ cứu nâng cao"],
    region: "Đà Nẵng",
    avatarUrl: null,
    note: "Điều dưỡng bệnh viện Đà Nẵng, đang hỗ trợ tại hiện trường",
  },
  {
    fullName: "Mai Xuân Trường",
    phone: "0889012345",
    email: "maixuantruong@gmail.com",
    secondaryPhone: null,
    address: "200 Nguyễn Trãi, Q.1, TP.HCM",
    role: "diver",
    status: "available",
    experienceLevel: "lead",
    certifications: [
      "Bằng lặn PADI Master",
      "Chứng nhận cứu hộ biển quốc tế",
      "HL tìm kiếm dưới nước",
    ],
    region: "Hồ Chí Minh",
    avatarUrl: null,
    note: "Trưởng đội lặn tìm kiếm cứu nạn TP.HCM",
  },
  {
    fullName: "Trần Hoàng Nam",
    phone: "0890123456",
    email: "tranhoangnam@gmail.com",
    secondaryPhone: null,
    address: "33 Pasteur, Q.Ninh Kiều, Cần Thơ",
    role: "firefighter",
    status: "injured",
    experienceLevel: "intermediate",
    certifications: ["Bằng PCCC", "Chứng nhận sơ cứu cơ bản"],
    region: "Cần Thơ",
    avatarUrl: null,
    note: "Bị gãy tay trong nhiệm vụ cứu hộ tuần trước, đang phục hồi",
  },
  {
    fullName: "Lương Thị Hà",
    phone: "0867890123",
    email: "luongthiha@gmail.com",
    secondaryPhone: null,
    address: "99 Trần Hưng Đạo, Q.Hoàn Kiếm, Hà Nội",
    role: "logistics",
    status: "available",
    experienceLevel: "lead",
    certifications: [
      "Chứng nhận quản lý chuỗi cung ứng cứu trợ",
      "Bằng điều phối logistics UNDP",
    ],
    region: "Hà Nội",
    avatarUrl: null,
    note: "Cựu nhân viên UNDP, chuyên gia hậu cần cứu trợ nhân đạo",
  },
];
